### ISSUE TITLE
Ideas for v0.2

### ISSUE THREAD

**Issue by BelaRincewind** [cyclotron-bonn/nano_util_board#15]
- connect to Arduino via RJ45 on the board which can also be used as a power source

**Comment by BelaRincewind** [comment]
In a short presentation of the board it was commented that it would be helpful being able to hardware-reset the arduino from afar. That could be done via another RJ45 socket on the board which carries the serial signal and has one lane connected to one of the reset pins of the arduino.

**Comment by leloup314** [comment]
Reset can always be done by just connecting to the Arduino headers directly. In any case, a custom cable has to be used / made, therefore it is just as good to use the headers directly imo

**Comment by BelaRincewind** [comment]
But how would one activate those pins in case the arduino isn't responding?

**Comment by leloup314** [comment]
The hardware reset on the Arduino is done by pulling the RESET pin to GND. Therefore, you can just connect the pin headers RESET and GND to a wire each, solder these to a switch / button  which then shorts these pins on switch/push. This solution is still the same with an extra connector for reset

**Comment by leloup314** [comment]
Or are we talking about different things ? ;)

**Comment by BelaRincewind** [comment]
What I meant was, that if the arduino is somewhere not accessable during an active beam one should still be able to reset it from the controlroom

**Comment by leloup314** [comment]
Ok, I mean the same :) We can just use a cable as I said, patch it through the patch panel, and connect it to the GND and RESET pins, the short it via a button in the control room

**Comment by leloup314** [comment]
Closing since v.02 is over ;)
