### ISSUE TITLE
TEST: Frequency counting

### ISSUE THREAD

**Issue by leloup314** [cyclotron-bonn/nano_util_board#19]
Please test whether the frequency counting works with the PCB / Nano.

**Comment by BelaRincewind** [comment]
I will try to work look into the issues I had while testing -> Communication with Arduino. From the pcb side, it should work, but who knows.

**Comment by BelaRincewind** [comment]
Was there a test confirming the Freq count works? Considering the feedback with the wrong pin, someone tried it out.

**Comment by BelaRincewind** [comment]
Internal communication confirmed working frequency counting :)
