### ISSUE TITLE
QUESTION: Resistor dimensions and arrangement of components 

### ISSUE THREAD

**Issue by leloup314** [cyclotron-bonn/nano_util_board#3]
- Are you using 0603 footprints for the 10k resistors?
- Can you arrange the pin headers, that make all pins of the Nano available,  symmetrically around the Nano board?
- What is the current size of the PCB? Maybe you can make it a little bigger for the sake of accessibility when e.g. connecting NTCs

**Comment by BelaRincewind** [comment]
- yes, at least I think so. Their size is roughly 1.4x0.7 mm^2
- ok, I rearranged most stuff so it fits onto a smaller PCB, but I guess accessability is important
- around 7.5x6 cm^2
